// File used to test routes

###
GET http://localhost:3333/classes?week_day=1
  &subject=Física
  &time=9:00

###
POST http://localhost:3333/classes HTTP/1.1
Content-Type: application/json

  {
    "name": "Flash",
    "avatar": "https://spinoff.com.br/wp-content/uploads/The-Flash-2-1200x900.jpg",
    "whatsapp": "00123456789",
    "bio": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat laudantium",
    "subject": "Física",
    "cost": 80,
    "schedule": [
      { "week_day": 1, "from": "8:00", "to": "12:00" },
      { "week_day": 3, "from": "10:00", "to": "11:30" },
      { "week_day": 5, "from": "15:45", "to": "18:00" }
    ]
  }
